export const users = [
    {
        group_name: "portal_customization",
        id: 1,
        name: "Shalini Jain",
        email: "s.jain@test.com",
        address: "7778897584",
        age: 25,
        gender: "Female",
    },
    {
        group_name: "portal_customization",
        id: 2,
        name: "Dhruv Verma",
        email: "d.verma@test.com",
        address: "",
        phoneNo: "7776685782",
        age: 24,
        gender: "Male",
    },
    {
        group_name: "organizer",
        id: 3,
        name: "Prajwal Murthy",
        email: "p.murthy@test.com",
        address: "",
        phoneNo: "7776685782",
        age: 24,
        gender: "Male",
    },
    {
        group_name: "organizer",
        id: 4,
        name: "Avneet Singh",
        email: "a.singh@test.com",
        address: "",
        phoneNo: "7776685782",
        age: 24,
        gender: "Male",
    },
    {
        group_name: "organizer",
        id: 5,
        name: "Tushara Reddy",
        email: "t.reddy@test.com",
        address: "",
        phoneNo: "7776685782",
        age: 28,
        gender: "Female",
    },
];
